### ISSUE TITLE
[BUG] Scrappers disappear in late game

### ISSUE THREAD

**Issue by YShadow5Y** [hifoomin/WellRoundedBalance#19]
**Describe the bug**
The bug starts happening after ~15 minutes of gameplay. The first time it will presents itself when scrapping an item (the scrapper will disappear right after scrapping the first item). The scrappers that disappear are not interactable. While progressing, more and more scrapper will disappear at random, even disappearing as soon as next level is loaded. My friend noticed i was searching for scrappers, while passing right above them without noticing it. When he pinged the scrapper it appeard the indicator as if he pinged the ground. After ~45 minutes it looks like no scrapper spawns anymore, for me at least.

**Log**
[LogOutput.txt](https://github.com/hifoomin/WellRoundedBalance/files/11579264/LogOutput.txt)

**Additional context**
This bug was experienced while playing Multiplayer with my friend and **it only affects me**. The few mods installed apart from WellRoundedBalance and his required mods were LTGCapacitor, SillyItems, ItemStats, TeammateRevival, RTAutoSprintEx, THUDLenses. I was playing on really low graphics.
I discovered it right now, i will try to reproduce the bug in cheat mode and update this issue if i discover what's the cause.

**Comment by hifoomin** [comment]
Should finally be fixed - sorry for the looong delay
