### ISSUE TITLE
In multiplayer can't use scrapper and see printers

### ISSUE THREAD

**Issue by lisenokrusty** [hifoomin/WellRoundedBalance#23]
When we play in multiplayer, my friend cant use scrappers and see printers while im hosting, when he's hosting the problem is other way around. Even if i ping the printer my friend sees the "i want to move here ping" instead of the printer ping. i hope you will be able to address this issue and fix it!

**Comment by hifoomin** [comment]
Should finally be fixed - sorry for the looong delay
