### ISSUE TITLE
[BUG] Simulacrum softlocks when the mod is enabled

### ISSUE THREAD

**Issue by DBTDerpbox** [hifoomin/WellRoundedBalance#24]
**Describe the bug**
In Simulacrum, the game plays fine until the Focus tries to move. Once it tries to move the game completely softlocks, enemies stop spawning and the Focus will never move, resulting in the gamemode not being able to progress

**Log**
[simulacrum-log.txt](https://github.com/hifoomin/WellRoundedBalance/files/13880995/simulacrum-log.txt)

**Additional context**
The problem may not be immediately noticeable as you will need to play a few waves to make the Focus try to move

**Comment by hifoomin** [comment]
fixed in upcoming version, sorry for the LONG delay, ran into a ton of personal issues

**Comment by DBTDerpbox** [comment]
it's fine, I get it
